version: '3.3'

networks:
  frontend:
    ipam:
      config:
        - subnet: 10.20.0.0/24

services:
   loadbalancer:
     build: ./loadbalancer/
     container_name: production_haproxy
     networks:
       frontend:
         ipv4_address: 10.20.0.3
     environment:
       DOMAIN_NAME: rostnix.org.ua
       IP_POOL: 10.20.0.2
       URL: 
     ports:
       - 80:80
       - 443:443
       - 8000:8000

   nginx:
     build: ./web/
     container_name: production_nginx
     networks:
       frontend:
         ipv4_address: 10.20.0.2
     environment:
       DOMAIN_NAME: 
       WP_DATABASE: 
       WP_USERNAME: 
       WP_PASSWORD: 
       WP_HOST: 10.20.0.4
     expose:
       - 80
       - 443

   db:
     image: mariadb
     container_name: production_mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     networks:
       frontend:
         ipv4_address: 10.20.0.4
     environment:
       MYSQL_ROOT_PASSWORD: 
       MYSQL_DATABASE: 
       MYSQL_USER: 
       MYSQL_PASSWORD: 

volumes:
    db_data: {}
